### ISSUE TITLE
[Bug] Could not read JSON from special...

### ISSUE THREAD

**Issue by fedevx** [drinfernoo/plugin.program.autowidget#126]
I see actually two issues in one here. The first causes the second and I'm not sure it is triggered by me doing something or just part of the automatic refresh:

First, Autowidget fails to read what seems as a valid JSON file. The error shown in the log says:

`Could not read JSON from special://profile/addon_data/plugin.program.autowidget/2240a25ab3e8e53229c479bb86778e93a73a0171.history: Expecting ':' delimiter: line 2 column 14 (char 15)`

Looking at the JSON file, at the mentioned position (here is the head of the file in question):
`{
    "history": [
        [
            1648079605.6302774,
            "58c066a9cbdc9cf9710268246445a9ca0e64b6be"
        ],
        [
            1648080377.7382722,
            "5a821695dcf93ccb37b9ddec7345c390247e51fb"
        ],
        [
            1648080658.4945064,
            "5a821695dcf93ccb37b9ddec7345c390247e51fb"
        ],`

There is no error on line 2. I manually loaded the file using Python's json and it loaded it correctly. Maybe there is a problem with the method used to read the file ([utils.read_json](https://github.com/drinfernoo/plugin.program.autowidget/blob/d6acddf99bf630a52a74b65ffec06c9703f6c447/plugin.program.autowidget/resources/lib/common/utils.py#L458)).

As a consequence of the above, an exception is raised and caught, which returns None to the [cache.read_history](https://github.com/drinfernoo/plugin.program.autowidget/blob/d6acddf99bf630a52a74b65ffec06c9703f6c447/plugin.program.autowidget/resources/lib/common/cache.py#L73) method which in turn returns that to [push_cache_queue](https://github.com/drinfernoo/plugin.program.autowidget/blob/d6acddf99bf630a52a74b65ffec06c9703f6c447/plugin.program.autowidget/resources/lib/common/cache.py#L104) resulting in this other exception (uncaught):

`ERROR <general>: plugin.program.autowidget: Traceback (most recent call last):
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 80, in dispatch
                                                       is_dir, category, is_type = menu.merged_path(group, widget_id)
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 575, in merged_path
                                                       titles, cat, type = show_path(
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 314, in show_path
                                                       files, hash = refresh.get_files_list(path, path_label, widget_id)
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 329, in get_files_list
                                                       _, files, _ = cache.cache_expiry(path, widget_id, background=background)
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/common/cache.py", line 281, in cache_expiry
                                                       push_cache_queue(path)
                                                     File "/home/kodi/.kodi/addons/plugin.program.autowidget/resources/lib/common/cache.py", line 104, in push_cache_queue
                                                       if history.get("path", "") != path:
                                                   AttributeError: 'NoneType' object has no attribute 'get'
`

As a fix to the uncaught exception, I would suggest that if the JSON file can't be read the fie should be deleted and the method recalled with the same parameters it was originally called with. This would at least create a blank file and return it back rather than causing an abnormal termination.

**Expected behavior**
There should be no uncaught exceptions.

**Details:**
  - What version of Kodi?
      - 19.4-1
  - What skin is being used?
  -     Cosmic
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...)
  -     Raspberry Pi 4
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...)
  -     Linux

**Comment by drinfernoo** [comment]
Can you share an AutoWidget backup, or at least the `2240a25ab3e8e53229c479bb86778e93a73a0171.history` file?

**Comment by fedevx** [comment]
Couldn't find a backup, here is the history file.

[2240a25ab3e8e53229c479bb86778e93a73a0171.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/8346700/2240a25ab3e8e53229c479bb86778e93a73a0171.txt)

**Comment by drinfernoo** [comment]
You can create a backup from the add-on's settings... that file does look valid, so I'm really not sure what's going on there, without being able to see more of the other files.

**Comment by fedevx** [comment]
I had another error on a cache file.

`ERROR <general>: plugin.program.autowidget: Could not read JSON from special://profile/addon_data/plugin.program.autowidget/b713a524d3f1fb10762b2833a90c9bfdfbfaf6bd.cache: Expecting ':' delimiter: line 2947 column 34 (char 165145)`

Again, the file looks fine and python is able to parse it correctly. The file contents however is probably not something I should post here.

It does seem the error happens to others as well, you can see it [here](https://github.com/drinfernoo/plugin.program.autowidget/issues/107#issuecomment-917852628). The reason for the error in the post however is not correctly identified. In that post it says:

`AttributeError: 'NoneType' object has no attribute 'get'`

However is might be the same problem I'm reporting:

```
        queue_data = utils.read_json(path)
        yield queue_data.get("path", "")
```

queue_data doesn't have a "get" attribute because when util.read_json hits an exception when reading a file, it returns None (which of course doesn't have a "get" attribute).

And [here](https://github.com/drinfernoo/plugin.program.autowidget/issues/107#issuecomment-915033272) is another post of the same error.

I have not dug deeper into why the JSON file fails to be decoded (the files do look fine, maybe they are overwritten in a subsequent download) but maybe you can correct what happens when it does fail to decode it. Maybe utils.read_json should return `{}` instead of `None` or the methods making use of utils.read_json could handle better what to do when it returns None.

**Comment by drinfernoo** [comment]
I'll look into changing the default return value in case of failure, but I'll have to investigate other potential consequences of that beforehand.

Also, it is relatively odd that the JSON wouldn't be correctly parsed anyways, if it is indeed valid JSON.

Could you provide a full log?

**Comment by drinfernoo** [comment]
In the absence of a full log, can you try and test `0.0.1533` from the devrepo? I've made the change you suggested, and it doesn't *seem* like it will have an effect anywhere else that I can see right off. 

If that still doesn't help, please provide a full log 😉

**Comment by fedevx** [comment]
Yeah, I made some changes to the code myself so it would redownload the JSON file if it failed to read it. So while I still get the error, the file would be fixed right after. I'll get the new version and report back.

**Comment by djay** [comment]
fixed in https://github.com/drinfernoo/plugin.program.autowidget/pull/108

**Comment by drinfernoo** [comment]
@djay Interesting! I could see how that would help, but I need to review the refreshing code a little more thoroughly before merging. Sorry it's been so long!

**Comment by fedevx** [comment]
Seems this does it. The error still happens but now it is better handled. As for the reason of the error (which could be handled separately), could it be the plugin is trying to read a file while it is still being written? I have Kodi on a Raspberry Pi 4, so maybe in certain situations, writing the file would take longer than on a PC.

**Comment by fedevx** [comment]
It has been a while but I got around changing the code to save a copy of the JSON content that failed to be decoded just to see why it was failing. I'm still not sure how it came to happen but the JSON files that failed have binary data in them that breaks the JSON structure (a bunch of 00).

I'm attaching a sample.
[autowidget.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/9204245/autowidget.txt)

I'll keep an eye on new samples, see if it is always the same case.
