### ISSUE TITLE
[Bug] Errors in logs, likely also crashing Kodi

### ISSUE THREAD

**Issue by RandomGithubUsername** [drinfernoo/plugin.program.autowidget#58]
**Describe the bug**
Seeing these errors/exceptions in Kodi logs.

`2020-10-31 10:39:09.578 T:12775   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 275, in run
                                                cache_and_update(widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 288, in cache_and_update
                                                utils.cache_files(widget_path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/utils.py", line 381, in cache_files
                                                hash = hashlib.sha1(path).hexdigest()
                                            TypeError: sha1() argument 1 must be string or buffer, not list
2020-10-31 10:39:11.012 T:12767  NOTICE: plugin.program.autowidget: Read cache (exp in -14189.8583541s): 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-10-31 10:39:11.012 T:12767  NOTICE: plugin.program.autowidget: Queue cache update for: 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-10-31 10:39:11.026 T:12780   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 275, in run
                                                cache_and_update(widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 288, in cache_and_update
                                                utils.cache_files(widget_path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/utils.py", line 381, in cache_files
                                                hash = hashlib.sha1(path).hexdigest()
                                            TypeError: sha1() argument 1 must be string or buffer, not list
2020-10-31 10:39:11.457 T:12781  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recently_added-1602388236.31 ][ mode: path ][ id: 23bc1887-4a36-4bf1-829f-3e92d392176c ]
2020-10-31 10:39:11.695 T:12781  NOTICE: plugin.program.autowidget: Read cache (exp in -14181.3558881s): fb598fe8b72a34f4c351e591867c58e624ff5544
2020-10-31 10:39:11.695 T:12781  NOTICE: plugin.program.autowidget: Queue cache update for: fb598fe8b72a34f4c351e591867c58e624ff5544
2020-10-31 10:39:11.821 T:12785   ERROR: Exception in thread Thread-1:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 275, in run
                                                cache_and_update(widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 288, in cache_and_update
                                                utils.cache_files(widget_path)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/utils.py", line 381, in cache_files
                                                hash = hashlib.sha1(path).hexdigest()
                                            TypeError: sha1() argument 1 must be string or buffer, not list`

**Details:**
  - What version of Kodi? 18.8
  - What skin is being used? Arctic Horizon
  - What device? (PC, Smartphone, Fire TV, Nvidia Shield, etc...) Nvidia Shield
  - What platform? (Android, iOS, Windows, OS X, Linux, etc...) Android TV

**Comment by drinfernoo** [comment]
@djay, would you mind taking a quick look here?

**Comment by djay** [comment]
@drinfernoo ok. without knowing the widget being used it would be hard to reproduce. I'll look at the code and see if there is anyway a path can be a list. if you have any hints on how that can be, that would be helpful.

**Comment by drinfernoo** [comment]
Should be fixed in `3.0.2`.

**Comment by RandomGithubUsername** [comment]
This did not fix the issue. It even crashes Kodi. I have rolled back to version 2.x for now and disabled auto updates and its all good now.

**Comment by drinfernoo** [comment]
Can you provide a full log?
