### ISSUE TITLE
[Bug] Images of cast members won't display

### ISSUE THREAD

**Issue by rizreflects** [drinfernoo/plugin.program.autowidget#81]
I use the Arctic Horizon skin. When clicking movie info and then pressing down, it displays pictures of cast members. The image below explains what I mean. This widget was directly through seren.

![serencast-min](https://user-images.githubusercontent.com/76912707/107856884-31011f80-6e23-11eb-8828-cf60ba5a132c.PNG)

But when using Autowidget, for some reason the pictures never get displayed. See below.

![autowidgetcast](https://user-images.githubusercontent.com/76912707/107856942-79204200-6e23-11eb-9d10-d6e0ff146e72.PNG)

I'm not sure why this happens, but it's always been the case for me. Anyway this is a minor issue but something for you to potentially look into.

**Comment by drinfernoo** [comment]
This is because cast and crew are attached to the items as ListItem properties (by design), which are not passed through to AutoWidget properly, due to limitations Kodi's JSON-RPC API in version pre-Matrix. In Matrix, this has been resolved, but they will not show properly in Leia. It simply cannot be done.

**Comment by rizreflects** [comment]
Hey there, sorry to open the same closed topic.. but the problem persists even on matrix. I've attached pictures to this message. The actor thumbnails and the movie length are not shown at all. 

![IMG_20210309_011337](https://user-images.githubusercontent.com/76912707/110403449-021e4800-8075-11eb-9479-31c8ad8a025f.jpg)
![IMG_20210309_011347](https://user-images.githubusercontent.com/76912707/110403463-05b1cf00-8075-11eb-9e82-98cf910562fc.jpg)

Thanks a lot for your time.

**Comment by drinfernoo** [comment]
I'll have to look into this, but where is that item coming from (which add-on)?

**Comment by rizreflects** [comment]
Serens liked movie lists

**Comment by rizreflects** [comment]
https://1drv.ms/u/s!AgpGD5FbtkrWm3bGi8v5VE9ABMU4?e=KjqAI8

Thats the group file incase you need it.

**Comment by drinfernoo** [comment]
Actually, it's come to my attention that while there is actually a bug with the JSON-RPC method we use, which would keep certain things from working (which I'll fix shortly), *cast* information is not stored in that way... only the crew is.

As you can see from your screenshots, you *are* actually getting cast *information* (the name and role), but not the images... Which appear to not be passed properly by the JSON-RPC response.

Here is an example of the cast information that TMDbHelper uses *internally*, and is set to the items, which is why their images work:
```json
[
  {
    "name": "Dan Castellaneta",
    "role": "Homer Simpson",
    "order": 0,
    "thumbnail": "https://image.tmdb.org/t/p/w500/AmeqWhP4A46AWkM4kVphg6jOTQX.jpg"
  },
  {
    "name": "Julie Kavner",
    "role": "Marge Simpson",
    "order": 1,
    "thumbnail": "https://image.tmdb.org/t/p/w500/x3oG3OXtBfTFgqXPqxI1GKVEiaQ.jpg"
  },
  {
    "name": "Nancy Cartwright",
    "role": "Bart Simpson",
    "order": 2,
    "thumbnail": "https://image.tmdb.org/t/p/w500/40qNhyYJhSE2Yiy4pnXSZhdufO6.jpg"
  },
  {
    "name": "Yeardley Smith",
    "role": "Lisa Simpson",
    "order": 3,
    "thumbnail": "https://image.tmdb.org/t/p/w500/oACYQyA8k8oDaMxsbMRHz8OP6u2.jpg"
  },
  {
    "name": "Hank Azaria",
    "role": "Apu",
    "order": 7,
    "thumbnail": "https://image.tmdb.org/t/p/w500/khTCh9TUT5YgMNvteLAh0D9H4Ck.jpg"
  },
  {
    "name": "Harry Shearer",
    "role": "Ned Flanders",
    "order": 500,
    "thumbnail": "https://image.tmdb.org/t/p/w500/au1mO0Mb9gni7h0rJCSokBTDnVf.jpg"
  }
]
```

However, the same item from TMDbHelper (The Simpsons) returns this in the JSON-RPC `Files.GetDirectory` response:
```json
[
  {
    "name": "Dan Castellaneta",
    "order": 0,
    "role": "Homer Simpson"
  },
  {
    "name": "Julie Kavner",
    "order": 1,
    "role": "Marge Simpson"
  },
  {
    "name": "Nancy Cartwright",
    "order": 2,
    "role": "Bart Simpson"
  },
  {
    "name": "Yeardley Smith",
    "order": 3,
    "role": "Lisa Simpson"
  },
  {
    "name": "Hank Azaria",
    "order": 7,
    "role": "Apu"
  },
  {
    "name": "Harry Shearer",
    "order": 500,
    "role": "Ned Flanders"
  }
]
```

As I'm using TMDbHelper as an example here, I would be interested in @jurialmunkey's input, but it appears that **Kodi** is not returning the thumbnail in the response, even though it is set on the item. This may actually be a bug inside Kodi itself (or simply overlooked in the JSON-RPC) implementation... But I'm going to reopen this for now anyways.

**Comment by drinfernoo** [comment]
https://github.com/xbmc/xbmc/issues/19388

**Comment by drinfernoo** [comment]
While there is still a standing bug in Kodi that prevents this, a fix has apparently been found that should allow AutoWidget to get ahold of cast thumbnails. Aside from that, I found that some of the logic of applying them isn't quite right *in* AutoWidget, so I'll address that in the meantime, and hopefully get "ahead of the curve" 👍

**Comment by rizreflects** [comment]
Great to hear! Thanks for the update doc.

**Comment by drinfernoo** [comment]
To confirm, this actually appears to have already been fixed in Kodi 20, before we even got there. Unfortunately, those changes seem too big to backport to Matrix... so while AutoWidget will support cast thumbnails as of 3.3.0, the feature won't actually *work* unless running in a Kodi 20 instance (nightlies are a bit wonky, and stable is a ways off still).

**Comment by drinfernoo** [comment]
This feature is now supported (in Kodi 20 **only**) as of AutoWidget 3.3.0, so I'm closing this issue.
